### PR TITLE
add basic initialization tests

### PR DESCRIPTION
**Pull request by williamboman**

### CODE REVIEW

**Comment by williamboman** [comment]
Ok seems like we got something going now at least. Will stop pushing as to not trigger more actions 🤣 .

This is very much centered around nvim-lsp-installer for now as only servers supported by the installer is included. The Dockerfile was also just written as a short term measure to containerize a fully capable host environment (it's not optimized or really thought through). For cross platform and arch, it might be interesting to do this differently.

**Comment by williamboman** [comment]
I'll be able to use this locally for now, which helps tremendously with sweeping changes such as https://github.com/williamboman/nvim-lsp-installer/pull/283 but also observing the general health of the plugin. Will tune down my efforts on this a bit for the time being

**Comment by rish987** [comment]
Wow, that's a lot of tests. Thanks. Docker stuff is new to me but I'll take a look this weekend and see if I can get the gist of this.

**Comment by williamboman** [comment]
There's a lot of copy paste involved, with a very similar test file per server. The fixture files are pretty much the only thing that is unique per server, and they all follow the structure you already had in place:

```
fixtures/
- example-project-1/ 
    This contains the minimum required to constitute a "workspace" directory for the given server.
    Often, this is just a source file (either empty or with some basic Hello World contents) + a default root_dir trigger (this is mostly a single file).
- example-project-{n}/
    If it ever makes sense to test other scenarios, one could introduce new workspaces in these directories.
```

I decided to keep quite a lot of duplication in the test files, even though they're currently very parameterizable (I'm also not a fan of the DRY dogma, especially in tests). Having these in place also makes adding new, server-specific, tests much easier.

As for the Dockerfile, it only really serves as a temporary means to easily spin up an environment in which all servers can install & execute in. I'm sure it can be useful in the long run as well, but in the interest of promoting cross platform coverage, I think we should try to leverage GitHub actions and compose actions to create a fully capable environment.

All servers currently only test that the [initialize request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize) is successful (although tsserver and sumneko_lua both have some extra user interaction tests like hover and go to definition).

---

Also, I removed the lean server tests because there is no installer for them. So again, this is currently built around nvim-lsp-installer, although the tests themselves are very useful for lspconfig alone, but some work needs to be done to decouple nvim-lsp-installer from them.

**Comment by williamboman** [comment]
Also, before running the tests, the test files are moved to a tmpdir to make sure we don't accidentally trigger a root_dir trigger outside of the test workspace. I wonder if it'd make sense to be able to configure where lspconfig should terminate root_dir traversal, @mjlbach?

edit: This makes me realize we should assert the resolved workspace dir as part of the base test suite

**Comment by williamboman** [comment]
The Docker image was missing some runtime deps. Some of the tests that are now timing out are due to hard-coded timeout in plenary.nvim (https://github.com/nvim-lua/plenary.nvim/pull/285). Increasing that timeout makes these tests pass. IIRC, Volar is really the only server that actually seems problematic.

**Comment by williamboman** [comment]
FWIW I'll continue pushing to the `main` branch in https://github.com/williamboman/nvim-lspconfig-test as to not trigger more workflow runs in this repo. I'm currently setting up a scheduled job to run hourly or so on my old Mac server, will run "Linux" tests in a container and will also try to get my hands on a Windows VM. I might integrate direct reporting with https://github.com/williamboman/nvim-lsp-installer for visibility, but most likely I'll just settle with emails being sent to me on failures. Adding a new server is not an every day occurrence so I can live with the added manual overhead. But as said before, these tests are still very valid for lspconfig alone, as long as there's a way to install the server without nvim-lsp-installer.

**Comment by rish987** [comment]
Hey, sorry I got a bit swamped with family matters and thesis work this weekend. I'll probably get to this in the next few days.

**Comment by williamboman** [comment]
No worries at all mate! There is no rush here at all and I'm not expecting this PR to be merged as-is because there's still some work to do (not to mention addressing the failing servers). I'm still experimenting a bit and adding new servers as they get supported in nvim-lsp-installer, so I prefer to do that in a separate branch as to not pollute this one. I'd be more than happy to contribute changes upstream eventually.

I'm already running this on a scheduled basis locally, so in a sense we already have tests in place for a subset of lspconfig servers :)

**Pull request closed without merging**
